### PR TITLE
Make the `LoggingConnection` impl fully generic

### PR DESCRIPTION
**Pull request by weiznich**
In combination with https://github.com/diesel-rs/diesel/pull/2449 this provides a fully generic connection impl that is usable in all places that currently use any diesel connection

### CODE REVIEW

**Comment by aleshaleksey** [comment]
Could you bump the (major?) version in `Cargo.toml` as well?

Also, I probably will not be testing this properly till Monday (because it is meaningless to test these generic implications without trying to build `gst-database` with the crate...), so I don't know if you want me to merge it without full testing or what?

**Comment by aleshaleksey** [comment]
Also, I am afraid I am not 100% sure whether diesel#2449 will work with what we currently do in GST. So I'm going to have a very thorough look to make sure that *we* can use it in GST. If it turns out that we have to change a large number of things, it might be better to keep it as a separate branch, for two different types of user (modern `diesel` and old diesel).

**Comment by weiznich** [comment]
> Also, I am afraid I am not 100% sure whether diesel#2449 will work with what we currently do in GST. 

I haven't tested it, but I'm 99% sure that it will work, as I know both GST (especially the db part) and diesel quite well :wink:

> If it turns out that we have to change a large number of things, it might be better to keep it as a separate branch, for two different types of user (modern diesel and old diesel).

We need to change a "large" number of things: In detail:
* Cherry pick the diesel changes to our diesel fork 
* Update the used diesel version in diesel_logger, diesel-oci, in our diesel-dynamic-schema fork and in gst itself
* Update the used versions of diesel-oci, diesel-logger and diesel-dynamic-schema in gst itself.
* Update the usage of `LoggingConnection` in your PR to gst

Beside of that our custom diesel for is not a old diesel version, but in fact a quite recent one. We should try to update it regularly to diesels master branch to not fall to far back and have bigger maintenance problems there in the long run. Additionally I'm working on up streaming all required changes in some why so that we can just use diesel master (and later the next large release), but that probably needs some time...

> Could you bump the (major?) version in Cargo.toml as well?

Done

> Also, I probably will not be testing this properly till Monday (because it is meaningless to test these generic implications without trying to build gst-database with the crate...), so I don't know if you want me to merge it without full testing or what?

Should be tested and then merged. If you decide to go with your original version, please address the following points:

* No `Deref` impls for the underlying connection, have a distinct method  like `fn get_inner(&self) -> &C`
* The additional impls (`R2D2Connection`, `MigrationConnection`, `UpdateAndFetchResults`) for the logging connection should be shared between the different backend specific implementation, just call the corresponding impl on the inner connection
* It should be possible to compile this crate with all backends enabled
* `OciTransactionManager` can be accessed via the `TransactionManager` associated type in the `Connection` impl of `OciConnection` (so just `<OciConnection as Connection>::TransactionManager` to access that type)

**Comment by aleshaleksey** [comment]
I am closing this pull to master in favour of `callthrough-begin_test_transaction`. It is a good basis, but for our use of oracle the extra implementation of `begin_test_transaction` is crucial.

**Pull request closed without merging**
